[package]
name = "pwm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
aes-gcm = "0.10.3"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
rand = "0.8"
base64 = "0.21"
